Proguard: keep classes needed for kotlin-annotation-processing
Analysis API uses some symbols from intellij-core and
kotlinx-collections-immutable which are not used anywhere else in the
compiler, so they were stripped by proguard. This led to
NoSuchMethodError from kapt when it linked against a proguarded
compiler.